$GVCompanyname = "CmdCtrl4U" # Your company name. Name must be without spaces and special characters.
$GVAppName = "ConfirmLanguageSettings" # Name of the application. Name must be without spaces and special characters.
$GVhours = 4380 # Time frame, starting from installation date, within this script should run. 
$GVTestMode = $False # Set to $True to run in test mode, $False for production
$GVFQDN = "cmdctrl4u.net" # FQDN of your internal domain (to gather NTP servers)
$GVNTP1 = "ntp1.cmdctrl4u.net" # Primary NTP server (use internal ntp server if available, otherwise time.windows.com will be used)
$GVNTP2 = "ntp2.cmdctrl4u.net" # Secondary NTP server (use internal ntp server if available, otherwise time.windows.com will be used)
$GVIPv4Network = "10.189." # IPv4 network prefix for company network (check if on company LAN)
$GVIPv4ZScaler = "100.64." # IPv4 network prefix for Zscaler private access (check if on Zscaler private access/company LAN)
$GVDatacenter = "DatacenterLocationName" # Default datacenter location